---
layout: post
title: "Lesson XX: Julian Date"
date:   2015-10-19
authors: [Megan A. Jones, Marisa Guarinello, Courtney Soderberg]
contributors: 
dateCreated: 2015-10-22
lastModified: `r format(Sys.time(), "%Y-%m-%d")`
tags: [module-1]
packagesLibraries: 
category: 
description: "This lesson teaches individuals how to convert from calendar to
Julian dates."
code1:
image:
  feature: NEONCarpentryHeader_2.png
  credit: A collaboration between the National Ecological Observatory Network (NEON) and Data Carpentry
  creditlink: http://www.neoninc.org
permalink: /R/Plotting-Time-Series
comments: false
---


##Converting Between Time Formats - Julian days

Next, we will explore how to convert our time field to a different format. Heterogeneous
data often use different time formats. Thus, it is useful to know how to convert.
We will use Julian Days given we have some other data (NDVI) in Julian days that 
we'd like to compare to our data.

Julian days, as R interprets it, is a continuous count of the number of days 
beginning at Jan 1, each year. Thus each year will have up to 365 (non leap year)
or 366 (leap year) days. 

Note: This format can also be called ordinal day or year day, and, occasionally,
Julian day can refer to a numeric count since 1 January 4713 BC.
{ : .notice }

To quickly convert from month, day year to Julian days, can we use `yday`, a 
function from the `lubridate` library.

```{r julian-day-convert }
# convert to julian days
# to learn more about it type
?yday

harMet_15Min$julian <- yday(harMet_15Min$datetime)  
#make sure it worked all the way through.  Dataframe was 30 variables so julian should be 31st.
head(harMet_15Min$julian) 
tail(harMet_15Min$julian)

```

#NOTE - doing this here doesn't really make sense fully given it removes time.
#i will see what happens in the next lesson.




